config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'auth/:provider/callback', to: 'sessions#create'
  get'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
 # resources :cands
  #resources :users
  #get "upload_photos/:id" , to: "users#upload_photos"
  get "welcome/:id" , to: "users#welcome"
  get "thank_you/:id" ,to: "users#thank_you"
  get "terms" ,to: "users#terms"
  get "block" , to: "users#block"
  get "find" ,to: "users#find"

 # post "upload_photos/:id" , to: "users#upload_photos"
  root :to => "users#error"
 # post "post_photos/:id"  , to: "users#post_photos"
 
  post '/webhooks/telegram_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' => 'webhooks#callback' #, as: :receive_webhooks
 #post "/webhooks/telegram_vbc43edbf1614a075954dvd4bfab34l1" => "webhooks#callback"
 
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dealrs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     
      <div id="user_nav" style="display:none">
          <% if current_user %>
            Signed in as <strong><%= current_user.name %></strong>!
            <%= link_to "התנתק", signout_path, id: "sign_out" %>
          <% else %>
          <%= link_to "התחבר עם פייסבוק", "/auth/facebook?user_id=#{1}", id: "sign_in" %>  
           
          <% end %>
        </div>
   
    
    <%= yield %>
  </body>
</html>